In [1]:
import pandas as pd
titanic = pd.read_csv("new_titanic.csv")

FileNotFoundError: [Errno 2] No such file or directory: 'new_titanic.csv'

In [3]:
agrupado = titanic.groupby("Sex")["Age"].mean().to_frame(name = "Media Idade")
   
vivos = titanic[titanic["Survived"] == 1 ].groupby("Sex").count() 
mortos = titanic[titanic["Survived"] == 0 ].groupby("Sex").count() 
agrupado["vivos"] = vivos["PassengerId"]
agrupado["mortos"] = mortos["PassengerId"]
print(agrupado)

        Media Idade  vivos  mortos
Sex
female    27.915709    233      81
male      30.726645    109     468

In [4]:
train = pd.read_csv("train.csv")
mulher = train.Sex[(titanic["Sex"] == "female")].count()
homen = train.Sex[(titanic["Sex"] == "male")].count() 
total = train.Sex[(titanic["Survived"])].count() 
print(round((mulher/total) * 100,2))
print(round((homen/total) * 100 , 2))

35.24
64.76

In [5]:
gatos = pd.read_csv("cat_breeds_clean.csv",sep=";")
cat = gatos[gatos["Breed"] == "Angora"].count()
europa = gatos[(gatos["Country"] == "France") | (gatos["Country"] == "Germany")].count()
cat_orange = gatos[gatos["Fur_colour_dominant"] == "red/creame"].drop_duplicates()


print(cat_orange)

Empty DataFrame
Columns: [Breed, Age_in_years, Age_in_months, Gender, Neutered_or_spayed, Body_length, Weight, Fur_colour_dominant, Fur_pattern, Eye_colour, Allowed_outdoor, Preferred_food, Owner_play_time_minutes, Sleep_time_hours, Country, Latitude, Longitude]
Index: []

In [6]:

cat_orange = gatos[gatos["Fur_colour_dominant"] == "red/cream"]
cat_orange.head()

,Breed,Age_in_years,Age_in_months,Gender,Neutered_or_spayed,Body_length,Weight,Fur_colour_dominant,Fur_pattern,Eye_colour,Allowed_outdoor,Preferred_food,Owner_play_time_minutes,Sleep_time_hours,Country,Latitude,Longitude
4,Angora,0.50,6,male,False,21,3.0,red/cream,tabby,green,False,wet,51,10,France,48.864716,2.349014
7,Angora,0.58,7,male,False,23,3.0,red/cream,solid,blue,False,wet,55,11,France,47.218371,-1.553621
14,Angora,1.33,16,male,True,30,3.5,red/cream,tabby,blue,False,dry,38,20,France,48.864716,2.349014
28,Angora,1.25,15,male,True,40,3.8,red/cream,tabby,blue,False,wet,35,17,France,45.763420,4.834277
52,Angora,2.25,27,male,False,38,4.6,red/cream,tabby,blue,False,wet,11,14,France,44.837789,-0.579180

In [7]:
matriz = gatos[gatos["Age_in_months"] > 6] 
matriz["razao"] = matriz["Weight"]/(matriz["Body_length"]/100)

matriz["razao"].head

C:\Users\disrct\AppData\Local\Temp\ipykernel_12612\344191953.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  matriz["razao"] = matriz["Weight"]/(matriz["Body_length"]/100)

<bound method NDFrame.head of 6       13.636364
7       13.043478
8       12.000000
9       12.000000
10      11.538462
          ...
1017    15.878049
1018    18.393939
1019     9.022222
1020    12.976744
1021    15.812500
Name: razao, Length: 994, dtype: float64>

In [ ]:
macho =  gatos[gatos["Gender"] == "male"] 
macho[["Breed","Age_in_months", "Weight"]].head(10)

     Breed  Age_in_months  Weight
1   Angora              4     2.5
2   Angora              6     2.8
4   Angora              6     3.0
6   Angora              7     3.0
7   Angora              7     3.0
11  Angora              8     3.3
12  Angora              9     3.3
13  Angora             13     3.2
14  Angora             16     3.5
15  Angora             10     3.4

In [27]:
cat = gatos[gatos["Breed"] == "Ragdoll"]
por = cat["Sleep_time_hours"] / 24 * 100
cat["porcentagem"] = por
cat[["Breed","Sleep_time_hours","porcentagem"]].head(10)

C:\Users\disrct\AppData\Local\Temp\ipykernel_12612\3344738197.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  cat["porcentagem"] = por

       Breed  Sleep_time_hours  porcentagem
606  Ragdoll                10    41.666667
607  Ragdoll                16    66.666667
608  Ragdoll                16    66.666667
609  Ragdoll                17    70.833333
610  Ragdoll                16    66.666667
611  Ragdoll                20    83.333333
612  Ragdoll                15    62.500000
613  Ragdoll                21    87.500000
614  Ragdoll                13    54.166667
615  Ragdoll                13    54.166667

In [38]:
total = cat["Body_length"].sum()
print(total)

17002

In [39]:
por = cat["Sleep_time_hours"].median()
print(por)

16.0